<?php
// Static SSB map for QRZ embeds. Reads the cache generated by build_cache.php.
const MAP_WIDTH = 900;
const MAP_HEIGHT = 425;
const MAP_LAT_MIN = -55;
const MAP_LAT_MAX = 85;
const QTH_CALL = 'LU2MET';
const QTH_GRID = 'FF57oc';

$cacheFile = __DIR__ . '/data/qso_cache.json';
$cache = file_exists($cacheFile) ? json_decode(file_get_contents($cacheFile), true) : null;
$qsos = is_array($cache['qsos'] ?? null) ? $cache['qsos'] : [];
$phoneModes = ['SSB', 'USB', 'LSB', 'FM', 'AM', 'CW'];
$bandColors = [
    '10M' => '#e45756',
    '15M' => '#f28e2b',
    '20M' => '#59a14f',
    '40M' => '#4e79a7',
    '80M' => '#7b61a8'
];

function gridCentre(string $grid): ?array {
    $value = strtoupper(preg_replace('/[^A-Z0-9]/', '', trim($grid)));
    if (strlen($value) < 4 || strlen($value) % 2 !== 0) return null;
    $lat = 0.0;
    $lon = 0.0;
    $latSize = 10.0;
    $lonSize = 20.0;
    $pairs = strlen($value) / 2;
    for ($index = 0; $index < $pairs; $index++) {
        $first = $value[$index * 2];
        $second = $value[$index * 2 + 1];
        $letters = $index % 2 === 0;
        $lonIndex = $letters ? ord($first) - 65 : intval($first);
        $latIndex = $letters ? ord($second) - 65 : intval($second);
        $maxIndex = $letters ? ($index === 0 ? 17 : 23) : 9;
        if ($lonIndex < 0 || $latIndex < 0 || $lonIndex > $maxIndex || $latIndex > $maxIndex) return null;
        $lon += $lonIndex * $lonSize;
        $lat += $latIndex * $latSize;
        if ($index < $pairs - 1) {
            if ($letters) {
                $lonSize /= 10;
                $latSize /= 10;
            } else {
                $lonSize /= 24;
                $latSize /= 24;
            }
        }
    }
    return [$lat - 90 + $latSize / 2, $lon - 180 + $lonSize / 2];
}

function shortestLongitude(float $longitude, float $origin): float {
    return $origin + fmod($longitude - $origin + 540, 360) - 180;
}

function greatCirclePoints(array $start, array $end, int $count = 48): array {
    $toRadians = M_PI / 180;
    $aLat = $start[0] * $toRadians;
    $aLon = $start[1] * $toRadians;
    $bLat = $end[0] * $toRadians;
    $bLon = $end[1] * $toRadians;
    $a = [cos($aLat) * cos($aLon), cos($aLat) * sin($aLon), sin($aLat)];
    $b = [cos($bLat) * cos($bLon), cos($bLat) * sin($bLon), sin($bLat)];
    $dot = max(-1, min(1, $a[0] * $b[0] + $a[1] * $b[1] + $a[2] * $b[2]));
    $angle = acos($dot);
    if ($angle < 0.000001) return [$start, $end];
    $sinAngle = sin($angle);
    $points = [];
    $previousLon = $start[1];
    for ($index = 0; $index <= $count; $index++) {
        $fraction = $index / $count;
        $firstWeight = sin((1 - $fraction) * $angle) / $sinAngle;
        $secondWeight = sin($fraction * $angle) / $sinAngle;
        $x = $firstWeight * $a[0] + $secondWeight * $b[0];
        $y = $firstWeight * $a[1] + $secondWeight * $b[1];
        $z = $firstWeight * $a[2] + $secondWeight * $b[2];
        $lon = atan2($y, $x) / $toRadians;
        $lon = shortestLongitude($lon, $previousLon);
        $previousLon = $lon;
        $points[] = [atan2($z, sqrt($x * $x + $y * $y)) / $toRadians, $lon];
    }
    return $points;
}

function esc(string $value): string {
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
}

$qth = gridCentre(QTH_GRID) ?: [-34.0, -58.0];
$groups = [];
foreach ($qsos as $qso) {
    $mode = strtoupper((string)($qso['mode'] ?? ''));
    if (!in_array($mode, $phoneModes, true) || empty($qso['grid'])) continue;
    $position = gridCentre((string)$qso['grid']);
    if ($position === null) continue;
    $position[1] = shortestLongitude($position[1], $qth[1]);
    $band = strtoupper((string)($qso['band'] ?? ''));
    $key = (string)($qso['call'] ?? '') . '|' . strtoupper((string)$qso['grid']) . '|' . $band;
    if (!isset($groups[$key])) $groups[$key] = ['qso' => $qso, 'position' => $position, 'band' => $band];
}

$west = $qth[1] - 180;
$worldQthX = ($qth[1] + 180) / 360 * MAP_WIDTH;
$backgroundOffset = MAP_WIDTH / 2 - $worldQthX;
$backgroundUrl = 'https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/export?' . http_build_query([
    'bbox' => '-180,' . MAP_LAT_MIN . ',180,' . MAP_LAT_MAX,
    'bboxSR' => 4326,
    'size' => MAP_WIDTH . ',' . MAP_HEIGHT,
    'adjustAspectRatio' => 'false',
    'format' => 'png',
    'f' => 'image'
]);
function mapX(float $longitude): float { global $west; return ($longitude - $west) / 360 * MAP_WIDTH; }
function mapY(float $latitude): float { return (MAP_LAT_MAX - $latitude) / (MAP_LAT_MAX - MAP_LAT_MIN) * MAP_HEIGHT; }
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=900">
<title><?php echo esc(QTH_CALL); ?> SSB map</title>
<style>
html, body { margin: 0; padding: 0; background: #d9e2e5; }
.qrz-map { position: relative; width: 900px; height: 425px; overflow: hidden; font: 14px Arial, sans-serif; }
.qrz-map-background { position: absolute; inset: 0; width: 900px; height: 425px; background-image: url('<?php echo $backgroundUrl; ?>'); background-position: <?php echo round($backgroundOffset, 1); ?>px 0; background-repeat: repeat-x; background-size: 900px 425px; }
.qrz-map-background::before { left: -900px; }
.qrz-map-background::after { left: 900px; }
.qrz-map-lines { position: absolute; inset: 0; width: 900px; height: 425px; pointer-events: none; }
.qrz-map-points { position: absolute; inset: 0; width: 900px; height: 425px; }
.qrz-map-point { position: absolute; width: 8px; height: 8px; margin: -4px 0 0 -4px; border: 1px solid #fff; border-radius: 50%; box-shadow: 0 1px 3px #333; }
.qrz-map-qth { background: #f3c969; border-color: #18343a; width: 10px; height: 10px; margin: -5px 0 0 -5px; }
.qrz-map-label { position: absolute; left: 10px; top: 10px; padding: 7px 10px; color: #18343a; background: rgba(255,255,255,.92); border-radius: 4px; font-weight: bold; }
.qrz-map-count { font-weight: normal; }
</style>
</head>
<body>
<div class="qrz-map">
    <div class="qrz-map-background" role="img" aria-label="World map"></div>
    <svg class="qrz-map-lines" viewBox="0 0 900 500" aria-hidden="true">
<?php foreach ($groups as $group):
    $points = greatCirclePoints($qth, $group['position']);
    $path = [];
    foreach ($points as $point) $path[] = round(mapX($point[1]), 1) . ',' . round(mapY($point[0]), 1);
    $color = $bandColors[$group['band']] ?? '#68747d';
    for ($copy = -1; $copy <= 1; $copy++):
?>
        <polyline transform="translate(<?php echo $copy * MAP_WIDTH; ?> 0)" points="<?php echo esc(implode(' ', $path)); ?>" fill="none" stroke="<?php echo esc($color); ?>" stroke-width="1" stroke-opacity=".75" />
<?php endfor; endforeach; ?>
    </svg>
    <div class="qrz-map-points">
    <?php for ($copy = -1; $copy <= 1; $copy++): ?>
        <div class="qrz-map-point qrz-map-qth" style="left:<?php echo round(MAP_WIDTH / 2 + $copy * MAP_WIDTH, 1); ?>px;top:<?php echo round(mapY($qth[0]), 1); ?>px" title="<?php echo esc(QTH_CALL . ' ' . QTH_GRID); ?>"></div>
<?php foreach ($groups as $group):
    $qso = $group['qso'];
    $color = $bandColors[$group['band']] ?? '#68747d';
    $label = ($qso['call'] ?? '') . ' ' . ($qso['grid'] ?? '') . ' ' . $group['band'];
?>
    <div class="qrz-map-point" style="left:<?php echo round(mapX($group['position'][1]) + $copy * MAP_WIDTH, 1); ?>px;top:<?php echo round(mapY($group['position'][0]), 1); ?>px;background:<?php echo esc($color); ?>" title="<?php echo esc($label); ?>"></div>
<?php endforeach; endfor; ?>
    </div>
    <div class="qrz-map-label">LU2MET SSB <span class="qrz-map-count"><?php echo count($groups); ?> locations</span></div>
</div>
</body>
</html>
